#pragma once

#include <memory>
#include <optional>
#include <vector>

#include "novaphy/core/contact.h"
#include "novaphy/core/control.h"
#include "novaphy/core/model.h"
#include "novaphy/multibody/multibody_solver.h"
#include "novaphy/dynamics/solver_base.h"
#include "novaphy/dynamics/solver_sequential_impulse.h"
#include "novaphy/dynamics/xpbd_solver.h"
#include "novaphy/fluid/boundary.h"
#include "novaphy/fluid/particle_state.h"
#include "novaphy/fluid/pbf_solver.h"
#include "novaphy/fluid/neighbor_search.h"
#include "novaphy/sim/performance_monitor.h"
#include "novaphy/sim/state.h"

namespace novaphy {

/**
 * @brief High-level simulation container with pluggable solver.
 *
 * @details Owns an immutable model and delegates stepping to a
 * `SolverBase`-derived solver. The default solver is
 * `SolverSequentialImpulse` (PGS contact solver).
 *
 * If no solver is explicitly provided, a `SolverSequentialImpulse` is
 * created with default settings. Alternatively, callers can supply any
 * `SolverBase` subclass via `std::unique_ptr`.
 */
class World {
public:
    /**
     * @brief Construct a unified world.
     *
     * @param [in] model Immutable body/shape/articulation/fluid model definition.
     * @param [in] solver_settings Contact-solver tuning parameters for free rigid bodies.
     * @param [in] xpbd_settings XPBD solver settings for articulations.
     * @param [in] pbf_settings PBF solver settings for fluid particles.
     * @param [in] fluid_boundary_extent Half-extent for plane boundary sampling (m).
     * @param [in] multibody_settings Multibody PGS solver settings. 
     */
    explicit World(const Model& model, 
                   SolverSettings solver_settings = {},
                   XPBDSolverSettings xpbd_settings = {},
                   PBFSettings pbf_settings = {},
                   float fluid_boundary_extent = 1.0f,
                   std::optional<MultiBodySolverSettings> multibody_settings = std::nullopt);

    /**
     * @brief Advance the simulation by one time step using internal state.
     *
     * @param [in] dt Time step in seconds.
     */
    void step(float dt);

    /**
     * @brief Advance the simulation by one time step (explicit state variant).
     *
     * @param [in,out] state   Mutable simulation state.
     * @param [in]     control External control inputs.
     * @param [in]     dt      Time step in seconds.
     */
    void step(SimState& state, const Control& control, float dt);

    /**
     * @brief Set the world gravity vector.
     *
     * @param [in] g Gravity in world frame (m/s^2).
     */
    void set_gravity(const Vec3f& g);

    /**
     * @brief Get the current world gravity vector.
     *
     * @return Gravity in world frame (m/s^2).
     */
    const Vec3f& gravity() const { return gravity_; }

    /** @brief Mutable access to simulation state buffers. */
    SimState& state() { return state_; }
    /** @brief Read-only access to simulation state buffers. */
    const SimState& state() const { return state_; }

    /** @brief Access the immutable model definition. */
    const Model& model() const { return model_; }

    /** @brief Access the active solver. */
    SolverBase& solver() { return *solver_; }
    const SolverBase& solver() const { return *solver_; }

    /** @brief Contact points generated by the rigid body solver. */
    const std::vector<ContactPoint>& contacts() const { return solver_->contacts(); }

    /** @brief Mutable access to the articulated XPBD solver. */
    XPBDSolver& xpbd_solver() { return xpbd_solver_; }
    const XPBDSolver& xpbd_solver() const { return xpbd_solver_; }

    /** @brief Access the multibody solver (nullptr if not active). */
    MultiBodySolver* multibody_solver() { return multibody_solver_.get(); }
    const MultiBodySolver* multibody_solver() const { return multibody_solver_.get(); }

    /** @brief Mutable access to the fluid PBF solver. */
    PBFSolver& pbf_solver() { return pbf_solver_; }
    const PBFSolver& pbf_solver() const { return pbf_solver_; }

    /** @brief Mutable access to contact-solver settings (convenience for SolverSequentialImpulse). */
    SolverSettings& solver_settings();

    /** @brief Read-only access to fluid boundary particles. */
    const std::vector<BoundaryParticle>& boundary_particles() const { return boundary_particles_; }

    /** @brief Access the runtime performance monitor. */
    PerformanceMonitor& performance_monitor() { return performance_monitor_; }
    const PerformanceMonitor& performance_monitor() const { return performance_monitor_; }

    /**
     * @brief Accumulate an external force for the next integration step.
     *
     * @param [in] body_index Body index.
     * @param [in] force Force in world frame (N).
     */
    void apply_force(int body_index, const Vec3f& force);

    /**
     * @brief Accumulate an external torque for the next integration step.
     *
     * @param [in] body_index Body index.
     * @param [in] torque Torque in world frame (N*m).
     */
    void apply_torque(int body_index, const Vec3f& torque);

protected:
    void apply_fluid_boundary_density(SimState& state, const std::vector<Vec3f>& boundary_world_pos);
    void apply_fluid_coupling_forces(SimState& state, const std::vector<Vec3f>& boundary_world_pos, float dt);

    Model model_;
    SimState state_;
    Control control_; // User control input buffer

    // Sub-solvers
    std::unique_ptr<SolverBase> solver_;           // Rigid body solver
    XPBDSolver xpbd_solver_;                        // Articulated tree solver (XPBD path)
    std::unique_ptr<MultiBodySolver> multibody_solver_; // Articulated solver (ABA+PGS path)
    PBFSolver pbf_solver_;                          // Fluid SPH solver

    // Fluid boundary tracking
    std::vector<BoundaryParticle> boundary_particles_;
    SpatialHashGrid boundary_grid_;
    float particle_spacing_ = 0.02f;
    float particle_mass_ = 0.0f;
    Vec3f gravity_ = Vec3f(0.0f, -9.81f, 0.0f);

    PerformanceMonitor performance_monitor_;
};

}  // namespace novaphy
